### ISSUE TITLE
Control for asynchronous requests

### ISSUE THREAD

**Issue by merlos** [liferay/lexicon#124]
Hi!
I'm wondering if you'll provide some builtin functionality on the framework to provide visual feedback to the user while running AJAX processes. 

For example, if the user hits a button that submits a form through AJAX, while the AJAX request is being processed the UI displays something to tell the user that an action is being done (typically some kind of  spinning wheel or an state button like http://getbootstrap.com/javascript/#buttons-stateful)

Thanks. Juan.

**Comment by natecavanaugh** [comment]
Hi Juan,
We've been discussing this, and are planning on having something as far as loading indicators go.
Since the Lexicon implementation is currently based on Bootstrap, you can use the state button you pointed to as well, and it will work fine.

I'll leave this open for now, though, since we want to include loading icons for a few different scenarios as well.

Thanks Juan :)

**Comment by natecavanaugh** [comment]
Hi Juan,
I'm going to go ahead and close this one out, as we now have loading indicators (though we're still working on the documentation for it, but you can see the examples here: http://liferay.github.io/lexicon/content/loaders/).

If you feel this isn't quite what you wanted, please feel free to reopen the issue or create a new one.

Thanks Juan,
